### ISSUE TITLE
TypeError: main is not JSON serializable from REST api

### ISSUE THREAD

**Issue by gschrader** [airbnb/superset#1264]
I'm trying to see if I can create my tables using the REST api discussed in #279 however when I access the `/tablemodelview/api/read` endpoint I get the following exception.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 52, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask_appbuilder/views.py", line 229, in api_read
    result=result)
  File "/usr/local/lib/python2.7/site-packages/flask/json.py", line 266, in jsonify
    (dumps(data, indent=indent, separators=separators), '\n'),
  File "/usr/local/lib/python2.7/site-packages/flask/json.py", line 126, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/simplejson/__init__.py", line 397, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python2.7/site-packages/simplejson/encoder.py", line 275, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python2.7/site-packages/simplejson/encoder.py", line 357, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python2.7/site-packages/flask/json.py", line 83, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python2.7/site-packages/simplejson/encoder.py", line 252, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: main is not JSON serializable
```

Any ideas what the problem might be?

**Comment by gschrader** [comment]
Unfortunately this still occurs in version 0.11.

**Comment by gschrader** [comment]
This is still an issue in 0.12, I'd like to be able to help but I'm failing to see the main variable being defined in TableModelView.

**Comment by gschrader** [comment]
Still occurs in 17.6, I'm guessing that nobody actually uses the REST api for this sort of thing. I guess I'll see what my other options are to automate creating tables.

**Comment by gschrader** [comment]
I'm opting to write to the sqllite database directly.

**Comment by eeve** [comment]
I also encountered this error

`http://0.0.0.0:8088/druiddatasourcemodelview/api/read` endpoint throw  `is not JSON serializable`

stack:
```
...
...
File "/usr/local/superset/venv/lib/python3.5/site-packages/simplejson/encoder.py", line 697, in _iterencode
    o = _default(o)
  File "/usr/local/superset/venv/lib/python3.5/site-packages/flask/json.py", line 80, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/local/superset/venv/lib/python3.5/site-packages/simplejson/encoder.py", line 268, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: data_demo is not JSON serializable
```

**Comment by mistercrunch** [comment]
I've found that to make the free REST api usable in FAB, we often have to create an alternate ModelView for it.

For example, for the Dashboard model, we create a ModelView for the CRUD here:
https://github.com/airbnb/superset/blob/master/superset/views/core.py#L133

Then we create another ModelView for the REST API that exposes a different set of columns:
https://github.com/airbnb/superset/blob/master/superset/views/core.py#L504

I don't think that the REST api we get for free out of FAB is super mature and I think we've only used it for read operation. Note that the URL mini-language (for filtering and sorting) isn't documented but is easy to reverse-engineer in the CRUD UI. By setting filters and sorting the table, you can look at the URL and copy paste that into your `/api/read?` queries

**Comment by gschrader** [comment]
@mistercrunch some of the api does actually work fine for read, however `tablemodelview` and apparently `druiddatasourcemodelview` throws the error.
