### ISSUE TITLE
Mapbox Error {"error": "'NoneType' object has no attribute 'sqla_col'"}

### ISSUE THREAD

**Issue by TimEbbers** [airbnb/superset#1864]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version 

airbnb_prod.0.15.0.1 

### Expected results

Create a mapbox item, with long and lat coordinates

### Actual results
Error  {"error": "'NoneType' object has no attribute 'sqla_col'"}

![screencapture-10-10-14-31-8088-superset-explore-table-17-1482062871084](https://cloud.githubusercontent.com/assets/9339819/21293487/d416b536-c526-11e6-8694-e322babc80be.png)
### Steps to reproduce
If the query is done in table view the gps coordinates are displayed in Superset.
A query with gps coordinates > no result in mapbox element
In the mapbox when I press  the query button I get the error result:

{"error": "'NoneType' object has no attribute 'sqla_col'"}

Stacktrace

         Traceback (most recent call last):
  File "/home/user/venv/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/venv/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/venv/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/venv/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/venv/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/venv/local/lib/python2.7/site-packages/superset/models.py", line 2287, in wrapper
    return f(*args, **kwargs)
  File "/home/user/venv/local/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/home/user/venv/local/lib/python2.7/site-packages/superset/views.py", line 1469, in explore
    payload = viz_obj.get_csv()
  File "/home/user/venv/local/lib/python2.7/site-packages/superset/viz.py", line 374, in get_csv
    df = self.get_df()
  File "/home/user/venv/local/lib/python2.7/site-packages/superset/viz.py", line 169, in get_df
    self.results = self.datasource.query(**query_obj)
  File "/home/user/venv/local/lib/python2.7/site-packages/superset/models.py", line 1023, in query
    metrics_exprs = [metrics_dict.get(m).sqla_col for m in metrics]
AttributeError: 'NoneType' object has no attribute 'sqla_col'

**Comment by mistercrunch** [comment]
Notice: this issue has been closed because it has been inactive for 491 days. Feel free to comment and request for this issue to be reopened.
