### ISSUE TITLE
the column char case make key error when creating  pivot_table

### ISSUE THREAD

**Issue by jiamo** [airbnb/superset#2008]
### Superset version
master branch

### error
the origin datafame get from sql:
```
2017-01-20 00:54:40,148:WARNING:Kylin:Transactional rollback is not supported
    AFFILIATE_ID  SUM__REVENUE_POINTS
0            1804                116578
1            1411                1114083

```
the traceback:
```
[224 rows x 2 columns]
2017-01-20 00:56:08,701:ERROR:root:"['sum__revenue_points'] not in index"
Traceback (most recent call last):
  File "/home/ubuntu/yxy_1/superset/superset/views.py", line 1406, in explore_json
    payload = viz_obj.get_payload()
  File "/home/ubuntu/yxy_1/superset/superset/viz.py", line 360, in get_payload
    data = self.get_data()
  File "/home/ubuntu/yxy_1/superset/superset/viz.py", line 593, in get_data
    margins=True,
  File "/home/ubuntu/.pyenv/versions/superset/lib/python3.5/site-packages/pandas/tools/pivot.py", line 158, in pivot_table
    margins_name=margins_name)
  File "/home/ubuntu/.pyenv/versions/superset/lib/python3.5/site-packages/pandas/tools/pivot.py", line 183, in _add_margins
    grand_margin = _compute_grand_margin(data, values, aggfunc, margins_name)
  File "/home/ubuntu/.pyenv/versions/superset/lib/python3.5/site-packages/pandas/tools/pivot.py", line 244, in _compute_grand_margin
    for k, v in data[values].iteritems():
  File "/home/ubuntu/.pyenv/versions/superset/lib/python3.5/site-packages/pandas/core/frame.py", line 1991, in __getitem__
    return self._getitem_array(key)
  File "/home/ubuntu/.pyenv/versions/superset/lib/python3.5/site-packages/pandas/core/frame.py", line 2035, in _getitem_array
    indexer = self.ix._convert_to_indexer(key, axis=1)
  File "/home/ubuntu/.pyenv/versions/superset/lib/python3.5/site-packages/pandas/core/indexing.py", line 1214, in _convert_to_indexer
    raise KeyError('%s not in index' % objarr[mask])
KeyError: "['sum__revenue_points'] not in index"
 
```

So, I need change column to `SUM__REVENUE_POINTS` to make it works.  
Maybe we should use low-case characters in our backend server when handing dataframe.

I also find another place have this issure too: In time seirse view

the origin dataframe is 

```
  __TIMESTAMP  SUM_REVENUE_POINTS  SUM_REVENUE_POINTS
0  2017-01-13             9535297              955297
```

but there is some place to using this lower space:

```
Traceback (most recent call last):
  File "/home/ubuntu/yxy_1/superset/superset/views.py", line 1406, in explore_json
    payload = viz_obj.get_payload()
  File "/home/ubuntu/yxy_1/superset/superset/viz.py", line 360, in get_payload
    data = self.get_data()
  File "/home/ubuntu/yxy_1/superset/superset/viz.py", line 1387, in get_data
    df = self.get_df()
  File "/home/ubuntu/yxy_1/superset/superset/viz.py", line 1329, in get_df
    values=metrics)
  File "/home/ubuntu/.pyenv/versions/superset/lib/python3.5/site-packages/pandas/tools/pivot.py", line 120, in pivot_table
    grouped = data.groupby(keys)
  File "/home/ubuntu/.pyenv/versions/superset/lib/python3.5/site-packages/pandas/core/generic.py", line 3778, in groupby
    **kwargs)
  File "/home/ubuntu/.pyenv/versions/superset/lib/python3.5/site-packages/pandas/core/groupby.py", line 1427, in groupby
    return klass(obj, by, **kwds)
  File "/home/ubuntu/.pyenv/versions/superset/lib/python3.5/site-packages/pandas/core/groupby.py", line 354, in __init__
    mutated=self.mutated)
  File "/home/ubuntu/.pyenv/versions/superset/lib/python3.5/site-packages/pandas/core/groupby.py", line 2383, in _get_grouper
    in_axis, name, gpr = True, gpr, obj[gpr]
  File "/home/ubuntu/.pyenv/versions/superset/lib/python3.5/site-packages/pandas/core/frame.py", line 1997, in __getitem__
    return self._getitem_column(key)
  File "/home/ubuntu/.pyenv/versions/superset/lib/python3.5/site-packages/pandas/core/frame.py", line 2009, in _getitem_column
    result = result[key]
  File "/home/ubuntu/.pyenv/versions/superset/lib/python3.5/site-packages/pandas/core/frame.py", line 1997, in __getitem__
    return self._getitem_column(key)
  File "/home/ubuntu/.pyenv/versions/superset/lib/python3.5/site-packages/pandas/core/frame.py", line 2004, in _getitem_column
    return self._get_item_cache(key)
  File "/home/ubuntu/.pyenv/versions/superset/lib/python3.5/site-packages/pandas/core/generic.py", line 1350, in _get_item_cache
    values = self._data.get(item)
  File "/home/ubuntu/.pyenv/versions/superset/lib/python3.5/site-packages/pandas/core/internals.py", line 3290, in get
    loc = self.items.get_loc(item)
  File "/home/ubuntu/.pyenv/versions/superset/lib/python3.5/site-packages/pandas/indexes/base.py", line 1947, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas/index.c:4154)
  File "pandas/index.pyx", line 159, in pandas.index.IndexEngine.get_loc (pandas/index.c:4018)
  File "pandas/hashtable.pyx", line 675, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12368)
  File "pandas/hashtable.pyx", line 683, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12322)
KeyError: '__timestamp'

```
However, this time I don't have place to change '__timestamp' to `__TIMESTAMP`.
I also find `DTTM_ALIAS = '__timestamp'`. So I can't get understand why the  dataframe created by superset have big case column `__TIMESTAMP`.

**Comment by imthegod** [comment]
Hi @jiamo ,

I am having a similar problem. When I try to visualize a time series line chart , I get an exception saying 
`2017-02-13 15:34:40,958:ERROR:root:'__timestamp'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pandas/indexes/base.py", line 1945, in get_loc
    return self._engine.get_loc(key)
  File "pandas/index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas/index.c:4154)
  File "pandas/index.pyx", line 159, in pandas.index.IndexEngine.get_loc (pandas/index.c:4018)
  File "pandas/hashtable.pyx", line 675, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12368)
  File "pandas/hashtable.pyx", line 683, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12322)
KeyError: '__timestamp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/superset/views.py", line 1406, in explore_json
    payload = viz_obj.get_payload()
  File "/usr/local/lib/python3.6/site-packages/superset/viz.py", line 360, in get_payload
    data = self.get_data()
  File "/usr/local/lib/python3.6/site-packages/superset/viz.py", line 1258, in get_data
    def get_data(self):
  File "/usr/local/lib/python3.6/site-packages/superset/viz.py", line 1169, in get_df
    columns=form_data.get('groupby'),
  File "/usr/local/lib/python3.6/site-packages/pandas/tools/pivot.py", line 120, in pivot_table
    grouped = data.groupby(keys)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/generic.py", line 3778, in groupby
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/groupby.py", line 1427, in groupby
    return klass(obj, by, **kwds)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/groupby.py", line 354, in __init__
    mutated=self.mutated)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/groupby.py", line 2383, in _get_grouper
    in_axis, name, gpr = True, gpr, obj[gpr]
  File "/usr/local/lib/python3.6/site-packages/pandas/core/frame.py", line 1997, in __getitem__
    return self._getitem_column(key)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/frame.py", line 2004, in _getitem_column
    return self._get_item_cache(key)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/generic.py", line 1350, in _get_item_cache
    values = self._data.get(item)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/internals.py", line 3290, in get
    loc = self.items.get_loc(item)
  File "/usr/local/lib/python3.6/site-packages/pandas/indexes/base.py", line 1947, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas/index.c:4154)
  File "pandas/index.pyx", line 159, in pandas.index.IndexEngine.get_loc (pandas/index.c:4018)
  File "pandas/hashtable.pyx", line 675, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12368)
  File "pandas/hashtable.pyx", line 683, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12322)
KeyError: '__timestamp'`

According to your post you solved it by correcting somewhere. Can you please help

**Comment by jiamo** [comment]
May be it is not fit for you:  here is

```
     def to_series(self, df, classed='', title_suffix=''):
@@ -1230,8 +1248,11 @@ class NVD3TimeSeriesViz(NVD3Viz):
             else:
                 cols.append(col)
         df.columns = cols
+        # add df
+        df.index = pd.to_datetime(df.index, utc=False)
         series = df.to_dict('series')

```

and somewhere:

```
 class BaseViz(object):

     """All visualizations derive this base class"""
@@ -223,6 +233,7 @@ class BaseViz(object):
                     df[DTTM_ALIAS] += timedelta(hours=self.datasource.offset)
             df.replace([np.inf, -np.inf], np.nan)
             df = df.fillna(0)
+        df.columns = [x.lower() for x in df.columns]

```
