### ISSUE TITLE
py3+ldap: error during new user registration

### ISSUE THREAD

**Issue by rumbin** [airbnb/superset#2190]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.15.4

### Expected results
Whe a not yet registered user enters his LDAP login credentials, a new user account is created and the login succeeds.

### Actual results
The login attempt results in the following error message:
```
Exception on /login/ [POST]
Traceback (most recent call last):
  File "/opt/apps/superset/venv_py3_superset/lib64/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/apps/superset/venv_py3_superset/lib64/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/apps/superset/venv_py3_superset/lib64/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/apps/superset/venv_py3_superset/lib64/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/opt/apps/superset/venv_py3_superset/lib64/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/apps/superset/venv_py3_superset/lib64/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/apps/superset/venv_py3_superset/lib64/python3.4/site-packages/flask_appbuilder/security/views.py", line 398, in login
    user = self.appbuilder.sm.auth_user_ldap(form.username.data, form.password.data)
  File "/opt/apps/superset/venv_py3_superset/lib64/python3.4/site-packages/flask_appbuilder/security/manager.py", line 631, in auth_user_ldap
    self.update_user_auth_stat(user)
  File "/opt/apps/superset/venv_py3_superset/lib64/python3.4/site-packages/flask_appbuilder/security/manager.py", line 488, in update_user_auth_stat
    if not user.login_count:
AttributeError: 'bool' object has no attribute 'login_count'
```

However, logging in with a user accound already known by superset works flawlessly.

### Steps to reproduce

For comparison:
* Have a working superset setup running in python 2.7 with LDAP authentification via python-ldap module.
* Ensure that new user registration is working.
* Console log shows something like:
```
2017-02-16 10:23:11,754:DEBUG:flask_appbuilder.security.manager:LDAP bind with: xxxxxx XXXXXX
2017-02-16 10:23:11,764:DEBUG:flask_appbuilder.security.manager:LDAP bind OK: xxxxxx@xxx.xx
2017-02-16 10:23:11,773:INFO:flask_appbuilder.security.sqla.manager:Added user xxxxxx
2017-02-16 10:23:11,778:INFO:flask_appbuilder.security.sqla.manager:Updated user Xxxx Xxxxx
```

Actual reproduction of the issue:
* Create a python 3.4 venv, using pyldap module instead of python-ldap which is not available for python3.
* Use the same configuration as in the python 2.7 setup.
* Try to register a new user by entering their login credentials.

**Comment by xrmx** [comment]
It's exploding in flask app builder, not in superset.

**Comment by tooptoop4** [comment]
has anyone solved this?
