### ISSUE TITLE
AttributeError: 'User' object has no attribute 'csrf_token'

### ISSUE THREAD

**Issue by misiek1205** [airbnb/superset#2232]
When i click on the Edit user button I got a error.

![alt tag](http://i66.tinypic.com/xqawqv.png)

This is the content of this error:
Sorry, something went wrong
500 - Internal Server Error
Stacktrace
```
         Traceback (most recent call last):
  File "/home/michal/Pobrane/superset/env/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/michal/Pobrane/superset/env/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/michal/Pobrane/superset/env/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/michal/Pobrane/superset/env/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/michal/Pobrane/superset/env/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/michal/Pobrane/superset/env/lib/python2.7/site-packages/Flask_AppBuilder-1.8.1-py2.7.egg/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/home/michal/Pobrane/superset/env/lib/python2.7/site-packages/Flask_AppBuilder-1.8.1-py2.7.egg/flask_appbuilder/views.py", line 59, in this_form_get
    self.form_get(form)
  File "/home/michal/Pobrane/superset/env/lib/python2.7/site-packages/Flask_AppBuilder-1.8.1-py2.7.egg/flask_appbuilder/security/views.py", line 102, in form_get
    form_field.data = getattr(item, key)
AttributeError: 'User' object has no attribute 'csrf_token'
```
All other features work good. My version of superset is 0.15.4.

**Comment by mistercrunch** [comment]
This may be a bug with FAB or your specific configuration (if any)

**Comment by eeve** [comment]
same question

**Comment by mistercrunch** [comment]
How can I reproduce this?

**Comment by gloryballet** [comment]
@mistercrunch WTF_CSRF_ENABLED = True

**Comment by misiek1205** [comment]
@gloryballet I change this option to True but i was still the same error. My solution is add '#' comment to line 102 "form_field.data = getattr(item, key)" in file located at: "/home/michal/Pobrane/superset/env/lib/python2.7/site-packages/Flask_AppBuilder-1.8.1-py2.7.egg/flask_appbuilder/security/views.py"
Now it's working good, error don't show.
Thans for help.

**Comment by popfido** [comment]
I got same problem with default configuration, the superset version is 0.17.2

**Comment by LoYoPP** [comment]
same problem +1 ， superset version： 0.17.4

**Comment by leshik** [comment]
I have the same problem with version 0.17.5, python 3.6.1. How can I help to reproduce it?

**Comment by S-YOU** [comment]
This feature is part of FAB (Flask-AppBuilder), which in turn rely on Flask-WTF, and WTFForms.

As far as I discovered, those environment variable names were changed and not sync anymore by the time of writing this.

Adding this to config.py will disable CSRF, which does not work ever.
```
WTF_CSRF_ENABLED = False
```

**Comment by S-YOU** [comment]
I sent a PR to F.A.B, which should fix that.

**Comment by mistercrunch** [comment]
I have merge rights on that repo, will review. I can't push a release though as I don't have rights on Pypi for that package and the unit tests are broken at the moment which is a blocker. 

It would be nice if FAB was more actively maintained. It's hard for me to take on a 3rd project...

**Comment by S-YOU** [comment]
@mistercrunch, sent a PR which fixed CI on FAB, with few tests ignored.

https://github.com/dpgaspar/Flask-AppBuilder/pull/458
https://travis-ci.org/dpgaspar/Flask-AppBuilder/builds/229645773
