### ISSUE TITLE
sql lab cannot find db, db can show in slice

### ISSUE THREAD

**Issue by jinleileiking** [airbnb/superset#2470]
```
2017-03-25 02:34:58,159:ERROR:root:No row was found for one()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/superset/views/core.py", line 107, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 52, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/superset/views/core.py", line 1285, in tables
    database = db.session.query(models.Database).filter_by(id=db_id).one()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2755, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()
2017-03-25 02:34:58,181:ERROR:root:No row was found for one()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/superset/views/core.py", line 107, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 52, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/superset/views/core.py", line 1271, in schemas
    .filter_by(id=db_id)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2755, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()
```

**Comment by pbamotra** [comment]
I added a redshift database, but on clicking the SQL lab it shows the same error as above. Were you able to resolve this?

**Comment by mistercrunch** [comment]
I just pushed this hotfix https://github.com/airbnb/superset/commit/9691234b7e33d8162253a6971f6eb298c037b748 that may help. Some database engines and sqlalchemy dialects may be less sensitive to wrong types.
