### ISSUE TITLE
'NoneType' object has no attribute 'upper'

### ISSUE THREAD

**Issue by rickyall** [airbnb/superset#2477]
when i connect to mysql and write a sql. I get the result, but when i click the visualize, it show me an error
```
Traceback (most recent call last):
  File "/Users/qisc/.pyenv/versions/miniconda3-4.1.11/lib/python3.5/site-packages/superset/viz.py", line 265, in get_payload
    df = self.get_df()
  File "/Users/qisc/.pyenv/versions/miniconda3-4.1.11/lib/python3.5/site-packages/superset/viz.py", line 109, in get_df
    self.results = self.datasource.query(query_obj)
  File "/Users/qisc/.pyenv/versions/miniconda3-4.1.11/lib/python3.5/site-packages/superset/connectors/sqla/models.py", line 525, in query
    sql = self.get_query_str(engine, qry_start_dttm, **query_obj)
  File "/Users/qisc/.pyenv/versions/miniconda3-4.1.11/lib/python3.5/site-packages/superset/connectors/sqla/models.py", line 429, in get_query_str
    time_filter = dttm_col.get_time_filter(from_dttm, to_dttm)
  File "/Users/qisc/.pyenv/versions/miniconda3-4.1.11/lib/python3.5/site-packages/superset/connectors/sqla/models.py", line 68, in get_time_filter
    col >= text(self.dttm_sql_literal(start_dttm)),
  File "/Users/qisc/.pyenv/versions/miniconda3-4.1.11/lib/python3.5/site-packages/superset/connectors/sqla/models.py", line 117, in dttm_sql_literal
    self.type, dttm)
  File "/Users/qisc/.pyenv/versions/miniconda3-4.1.11/lib/python3.5/site-packages/superset/db_engine_specs.py", line 239, in convert_dttm
    if target_type.upper() in ('DATETIME', 'DATE'):
AttributeError: 'NoneType' object has no attribute 'upper'
```

**Comment by mistercrunch** [comment]
https://github.com/airbnb/superset/commit/398036d77e0c817796e3735797eae56e80dce437

**Comment by chiangqiqi** [comment]
thx a lot, this did bring me a little trouble.
