### ISSUE TITLE
sql lab "AttributeError: 'NoneType' object has no attribute 'read'"

### ISSUE THREAD

**Issue by bbs2009** [airbnb/superset#2529]
Make sure these boxes are checked before submitting your issue - thank you!

- [Y ] I have checked the superset logs for python stacktraces and included it here as text if any
- [Y] I have reproduced the issue with at least the latest released version of superset
- [Y] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
{"GIT_SHA": "", "version": "0.17.2"}

### Expected results
Visualize the sql query

### Actual results

`
[2017-03-31 11:52:42,755] ERROR in app: Exception on /superset/sqllab_viz/ [POST]
Traceback (most recent call last):
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/superset/utils.py", line 553, in wraps
    return f(self, *args, **kwargs)
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/superset/models/core.py", line 765, in wrapper
    value = f(*args, **kwargs)
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/superset/views/core.py", line 1772, in sqllab_viz
    q = SupersetQuery(data.get('sql'))
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/superset/sql_parse.py", line 16, in __init__
    self._parsed = sqlparse.parse(self.sql)
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/sqlparse/__init__.py", line 28, in parse
    return tuple(parsestream(sql, encoding))
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/sqlparse/engine/__init__.py", line 54, in _group
    for stmt in stream:
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/sqlparse/engine/filter.py", line 82, in process
    for ttype, value in stream:
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/sqlparse/lexer.py", line 274, in streamer
    for i, t, v in self.get_tokens_unprocessed(text):
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/sqlparse/lexer.py", line 293, in get_tokens_unprocessed
    text = stream.read()
AttributeError: 'NoneType' object has no attribute 'read'
Exception on /superset/sqllab_viz/ [POST]
Traceback (most recent call last):
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/superset/utils.py", line 553, in wraps
    return f(self, *args, **kwargs)
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/superset/models/core.py", line 765, in wrapper
    value = f(*args, **kwargs)
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/superset/views/core.py", line 1772, in sqllab_viz
    q = SupersetQuery(data.get('sql'))
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/superset/sql_parse.py", line 16, in __init__
    self._parsed = sqlparse.parse(self.sql)
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/sqlparse/__init__.py", line 28, in parse
    return tuple(parsestream(sql, encoding))
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/sqlparse/engine/__init__.py", line 54, in _group
    for stmt in stream:
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/sqlparse/engine/filter.py", line 82, in process
    for ttype, value in stream:
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/sqlparse/lexer.py", line 274, in streamer
    for i, t, v in self.get_tokens_unprocessed(text):
  File "/data/work/virtualenvs/superset/lib/python2.7/site-packages/sqlparse/lexer.py", line 293, in get_tokens_unprocessed
    text = stream.read()
AttributeError: 'NoneType' object has no attribute 'read'
`

### Steps to reproduce
I am writing a simple query.

![default](https://cloud.githubusercontent.com/assets/11568424/24543475/7da5e572-1608-11e7-98af-cd7b00cd4e7b.png)

Then click on the button to visualize
![default](https://cloud.githubusercontent.com/assets/11568424/24543564/c6d2f230-1608-11e7-9a2b-7db188f7e799.png)

Nothing happens, but an error appears in the terminal

![default](https://cloud.githubusercontent.com/assets/11568424/24543667/12361004-1609-11e7-8e2e-62885723c395.png)

Thank you

**Comment by zhmg23** [comment]
Is the problem solved?
