### ISSUE TITLE
Error while trying to create a new slice

### ISSUE THREAD

**Issue by DevBlaaast** [airbnb/superset#2564]
Hello !

First, thanks for this awesome library :) I have a small error that I just encountered. I could work on a PR if you need, but I would just need a couple of directions.

### Superset version
0.17.3

### Expected results
Open the "new slice" form.

### Actual results
Error with this stacktrace :
```
  Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/superset/utils.py", line 553, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/superset/views/core.py", line 415, in add
    redirect_url = "/r/msg/?url={}&msg={}".format(url, msg)
UnboundLocalError: local variable 'url' referenced before assignment
```
Pointing to this line : https://github.com/airbnb/superset/blob/master/superset/views/core.py#L379

### Steps to reproduce
Just click on the "+" to create on new slice on the "slices" page.

Thanks

**Comment by mistercrunch** [comment]
https://github.com/airbnb/superset/pull/2565 should clarify things. 

Though it looks like you had an edge case error related to the fact that you have no data sources setup. Did you run `superset load_examples` as specified in the installation docs?

**Comment by DevBlaaast** [comment]
Yes I definitely did hit the edge case you mentioned, and no I did not load the examples on purpose.

I was just wondering if we wanted to fix it anyway
