### ISSUE TITLE
ImportError: No module named pythrifthiveapi.TCLIService

### ISSUE THREAD

**Issue by hungrytortoise** [airbnb/superset#2637]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
the lastest

### Expected results
content from hive table

### Actual results
![image](https://cloud.githubusercontent.com/assets/25096206/25124528/9096c3a4-245e-11e7-81fa-35042767f314.png)

### Steps to reproduce
when i started a hive query task,the cli shows error like following

Traceback (most recent call last):
  File "/home/wugui/opt/venv/lib/python2.7/site-packages/superset/views/core.py", line 1994, in sql_json
    query_id=query_id, return_results=True)
  File "/home/wugui/opt/venv/lib/python2.7/site-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/home/wugui/opt/venv/lib/python2.7/site-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/home/wugui/opt/venv/lib/python2.7/site-packages/superset/sql_lab.py", line 70, in get_sql_results
    db_engine_spec.patch()
  File "/home/wugui/opt/venv/lib/python2.7/site-packages/superset/db_engine_specs.py", line 568, in patch
    from superset.db_engines import hive as patched_hive
  File "/home/wugui/opt/venv/lib/python2.7/site-packages/superset/db_engines/hive.py", line 2, in <module>
    from pythrifthiveapi.TCLIService import ttypes
ImportError: No module named pythrifthiveapi.TCLIService

**Comment by hungrytortoise** [comment]
solution:pip install pythrifthiveapi
