### ISSUE TITLE
Exception: 'Query' object has no attribute 'status'

### ISSUE THREAD

**Issue by hungrytortoise** [airbnb/superset#2643]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
the lastest version

### Expected results
![image](https://cloud.githubusercontent.com/assets/25096206/25167206/238a6c9e-2511-11e7-8170-6baf12098295.png)
when i clicked query btn ,it worked normally.
however, when i change my sql like the picture shows,it does not work .

### Actual results
![image](https://cloud.githubusercontent.com/assets/25096206/25167301/8850641c-2511-11e7-896c-b179b6f9757c.png)

### Steps to reproduce

how to fix that.
thanks

**Comment by hungrytortoise** [comment]
![image](https://cloud.githubusercontent.com/assets/25096206/25167442/1d665034-2512-11e7-98af-0693c1c14c05.png)
and when i done same sql query in same table,it could show correct results.

**Comment by hungrytortoise** [comment]
tip: table student is a hive table,when i do same sql query in a mysql table,it is norml too.

**Comment by xrmx** [comment]
Any stacktrace in the logs? Which version of superset is this?

**Comment by yixinyiyide** [comment]
@xrmx , I met the same error, some logs below. 

2017-04-20 16:16:42,600:INFO:pyhive.hive:**SELECT tlh.visitdate, count(distinct tlh.useruid) cnt_user
  FROM bo.t_log_hive tlh**
 group by tlh.visitdate
2017-04-20 16:16:42,600:DEBUG:pyhive.hive:TExecuteStatementReq(confOverlay=None, sessionHandle=TSessionHandle(sessionId=THandleIdentifier(secret='=\x8eYLt;@q\x86z\x96H\xf5\xc3\x14\xb0', guid='\xdf\xaf\x04\xaf\xfe\xe3B\xfc\x8e\x81\x1d;2\xaaI\xd2')), runAsync=True, statement='SELECT tlh.visitdate, count(distinct tlh.useruid) cnt_user\n  FROM bo.t_log_hive tlh\n group by tlh.visitdate')
2017-04-20 16:16:42,684:DEBUG:pyhive.hive:TExecuteStatementResp(status=TStatus(errorCode=None, errorMessage=None, sqlState=None, infoMessages=None, statusCode=0), operationHandle=TOperationHandle(hasResultSet=True, modifiedRowCount=None, operationType=0, operationId=THandleIdentifier(secret='\r\xc0\x16\x9c,\xe9N\x83\x8a\x90\x81so4=N', guid='vvV\x818\xb2H\x1e\x86\xa1]\x0c\xf0\xaa[\xce')))
2017-04-20 16:16:42,685:INFO:root:Handling cursor
2017-04-20 16:16:47,691:DEBUG:pyhive.hive:TGetOperationStatusResp(status=TStatus(errorCode=None, errorMessage=None, sqlState=None, infoMessages=None, statusCode=0), operationState=1, errorMessage=None, sqlState=None, errorCode=None)
2017-04-20 16:16:47,692:ERROR:root:'Query' object has no attribute 'status'
Traceback (most recent call last):
  File "/opt/python/python2.7.13/lib/python2.7/site-packages/superset/sql_lab.py", line 138, in get_sql_results
    db_engine_spec.handle_cursor(cursor, query, session)
  File "/opt/python/python2.7.13/lib/python2.7/site-packages/superset/db_engine_specs.py", line 642, in handle_cursor
    if query.status == QueryStatus.STOPPED:
**AttributeError: 'Query' object has no attribute 'status'**
2017-04-20 16:16:47,720:ERROR:root:'Query' object has no attribute 'status'
Traceback (most recent call last):
  File "/opt/python/python2.7.13/lib/python2.7/site-packages/superset/views/core.py", line 1994, in sql_json
    query_id=query_id, return_results=True)
  File "/opt/python/python2.7.13/lib/python2.7/site-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/opt/python/python2.7.13/lib/python2.7/site-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/opt/python/python2.7.13/lib/python2.7/site-packages/superset/sql_lab.py", line 144, in get_sql_results
    handle_error(db_engine_spec.extract_error_message(e))
  File "/opt/python/python2.7.13/lib/python2.7/site-packages/superset/sql_lab.py", line 78, in handle_error
    raise Exception(query.error_message)
**Exception: 'Query' object has no attribute 'status'**

**Comment by hungrytortoise** [comment]
@xrmx  my superset version is 0.17.4

**Comment by hungrytortoise** [comment]
could u help me deal with that @xrmx

**Comment by xrmx** [comment]
Looks like a missing `superset db upgrade`, could you please try that?

**Comment by hungrytortoise** [comment]
i upgrade superset to 0.17.5 ,but problem still exists. @xrmx

**Comment by santhavathi** [comment]
Even I am getting the same error

**Comment by santhavathi** [comment]
@xrmx, will this be fixed anytime soon?
