### ISSUE TITLE
gamma role query in sql lab

### ISSUE THREAD

**Issue by qinzl1** [airbnb/superset#2659]
### Superset version
0.17

### Actual results
**error log:**
[2017-04-21 15:19:42,908] ERROR in app: Exception on /superset/sql_json/ [POST]
Traceback (most recent call last):
  File "/data/superset_venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/superset_venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/superset_venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/superset_venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/superset_venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/superset_venv/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 52, in wraps
    return f(self, *args, **kwargs)
  File "/data/superset_venv/lib/python2.7/site-packages/superset/models.py", line 2697, in wrapper
    value = f(*args, **kwargs)
  File "/data/superset_venv/lib/python2.7/site-packages/superset/views.py", line 2558, in sql_json
    rejected_tables = self.rejected_datasources(sql, mydb, schema)
  File "/data/superset_venv/lib/python2.7/site-packages/superset/views.py", line 117, in rejected_datasources
    self.datasource_access_by_fullname(database, t, schema)]
  File "/data/superset_venv/lib/python2.7/site-packages/superset/views.py", line 111, in datasource_access_by_fullname
    database, table_name, schema=table_schema)
  File "/data/superset_venv/lib/python2.7/site-packages/superset/views.py", line 94, in datasource_access_by_name
    datasources = SourceRegistry.query_datasources_by_name(
AttributeError: type object 'SourceRegistry' has no attribute 'query_datasources_by_name'

**Comment by xrmx** [comment]
Looks like a dup of #2516 . Please reopen if it's not fixed in latest release.
