### ISSUE TITLE
Hit 500 while accessing dashboard

### ISSUE THREAD

**Issue by tonyjiang** [airbnb/superset#2723]
### Superset version
superset (0.17.5)

### Expected results
To see dashboard load

### Actual results

**Sorry, something went wrong**
```
500 - Internal Server Error

Stacktrace

         Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.4/site-packages/superset/utils.py", line 573, in wraps
    return f(self, *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/superset/views/core.py", line 1662, in dashboard
    'datasources': {ds.uid: ds.data for ds in datasources},
  File "/usr/lib/python3.4/site-packages/superset/views/core.py", line 1662, in <dictcomp>
    'datasources': {ds.uid: ds.data for ds in datasources},
AttributeError: 'NoneType' object has no attribute 'data'
```

### Steps to reproduce
Not sure :( but could this: after I added a new column to a table from backend, it didn't show up in the column list and there is no *Refresh* button (this itself is a bug). So I deleted the table, **after** some charts were already built on top of it, then added it back. All the charts still work.

Then I kept working on the same dashboard. Lots of stuff. Then I got the 500 the second day.

So if this is the reason, the charts relying on the table should stop working right away, so I don't keep working on the same dashboard. Also, when I delete the table, there should be a popup message saying "These are the 3 charts built on top of this table, they won't work if you delete the table even if you add it back later".

**Comment by mistercrunch** [comment]
I'm pretty sure I recently fixed this on `master`. It happened when a datasource behind a Slice on a dash was deleted. Please confirm that it's fixed on master. Hopefully I can get a release out this week.
