### ISSUE TITLE
OperationalError: (sqlite3.OperationalError) no such column: query.end_result_backend_time

### ISSUE THREAD

**Issue by elkan1788** [airbnb/superset#2770]
Hi, guys. There had found new issue come back. Also the same environment: Centos7.2, Python2.7.5, superset0.18.2. When I click the menu (Manage-->Queries Or Query Lab-->Query Search) their all same throw an exception: OperationalError: (sqlite3.OperationalError) , The detail info see below:

![snapshot-2017-05-17-3.27.13.png](http://7xi700.com1.z0.glb.clouddn.com/snapshot-2017-05-17-3.27.13.png-alias "snapshot-2017-05-17-3.27.13.png")

```
2017-05-17 15:19:18,706:INFO:werkzeug:172.16.10.100 - - [17/May/2017 15:19:18] "GET /slicemodelview/list/ HTTP/1.1" 200 -
2017-05-17 15:19:31,416:INFO:werkzeug:172.16.10.100 - - [17/May/2017 15:19:31] "GET /queryview/list/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/views.py", line 450, in list
    widgets = self._list()
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/baseviews.py", line 870, in _list
    page_size=page_size)
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/baseviews.py", line 786, in _get_list_widget
    count, lst = self.datamodel.query(joined_filters, order_column, order_direction, page=page, page_size=page_size)
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/models/sqla/interface.py", line 112, in query
    return count, query.all()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2703, in all
    return list(self)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) no such column: query.end_result_backend_time [SQL: u'SELECT "query".id AS query_id, "query".client_id AS query_client_id, "query".database_id AS query_database_id, "query".tmp_table_name AS query_tmp_table_name, "query".user_id AS query_user_id, "query".status AS query_status, "query".tab_name AS query_tab_name, "query".sql_editor_id AS query_sql_editor_id, "query".schema AS query_schema, "query".sql AS query_sql, "query".select_sql AS query_select_sql, "query".executed_sql AS query_executed_sql, "query"."limit" AS query_limit, "query".limit_used AS query_limit_used, "query".select_as_cta AS query_select_as_cta, "query".select_as_cta_used AS query_select_as_cta_used, "query".progress AS query_progress, "query".rows AS query_rows, "query".error_message AS query_error_message, "query".results_key AS query_results_key, "query".start_time AS query_start_time, "query".start_running_time AS query_start_running_time, "query".end_time AS query_end_time, "query".end_result_backend_time AS query_end_result_backend_time, "query".changed_on AS query_changed_on \nFROM "query"\n LIMIT ? OFFSET ?'] [parameters: (100, 0)]
```

So is this a new issues in latest version? Waiting for you, thanks.

**Comment by xrmx** [comment]
Looks like you missed to run migrations with `superset db upgrade` after upgrading to 0.18.2. See http://airbnb.io/superset/installation.html#upgrading

**Comment by elkan1788** [comment]
Got it. Thanks.
