### ISSUE TITLE
[explore] fetching of column values for filters not working with superset views

### ISSUE THREAD

**Issue by rumbin** [airbnb/superset#2810]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.2

### Expected results
Tables defined via SQL statement (superset view), e.g. via the visualize workflow from SQLLab, should behave like regular tables or views with respect to the filter select functionality in explore view.
I.e., fetching on distinct column values should succeed.

### Actual results
Fetching of distinct column values fails because the SQL query is not run agains the superset view as a subquery, but against the table name. In general, this table is of course not known by the SQL server.

`sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "test_superset_view" does not exist`

### Steps to reproduce

* Create a superset view, e.g. via the visualize workflow from SQLLab and enable Filter Select for this table.
* Explore the table and try to add a filter on any filterable column.

**Comment by mistercrunch** [comment]
This looks postgres specific, can you please share the full stacktrace from the web server?

**Comment by rumbin** [comment]
It is definitely not postgres specific. I just tested it with a fresh installation, using nothing but the default SQLite database.

## Steps to reproduce

* Run this query in SQLLab on the main (superset) database:
```
SELECT id,
       name
FROM main.ab_role
```
* Create a superset view out of it via _visualize_, naming the table _test_superset_view_ (just for further reference)
* Enable Filter Select for this table
* _explore_ the table and try to select filters on either of the two columns
```
2017-05-25 07:08:35,381:ERROR:root:(sqlite3.OperationalError) no such table: test_superset_view [SQL: 'SELECT DISTINCT id AS id \nFROM test_superset_view\n LIMIT 10000 OFFSET 0']
Traceback (most recent call last):
  File "/opt/apps/superset/venv_py3_test/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/opt/apps/superset/venv_py3_test/lib64/python3.4/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: test_superset_view

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/apps/superset/venv_py3_test/lib64/python3.4/site-packages/superset/views/base.py", line 49, in wraps
    return f(self, *args, **kwargs)
  File "/opt/apps/superset/venv_py3_test/lib64/python3.4/site-packages/flask_appbuilder/security/decorators.py", line 52, in wraps
    return f(self, *args, **kwargs)
  File "/opt/apps/superset/venv_py3_test/lib64/python3.4/site-packages/superset/views/core.py", line 1090, in filter
    payload = json.dumps(datasource.values_for_column(column))
  File "/opt/apps/superset/venv_py3_test/lib64/python3.4/site-packages/superset/connectors/sqla/models.py", line 314, in values_for_column
    df = pd.read_sql_query(sql=sql, con=engine)
  File "/opt/apps/superset/venv_py3_test/lib64/python3.4/site-packages/pandas/io/sql.py", line 331, in read_sql_query
    parse_dates=parse_dates, chunksize=chunksize)
  File "/opt/apps/superset/venv_py3_test/lib64/python3.4/site-packages/pandas/io/sql.py", line 1084, in read_query
    result = self.execute(*args)
  File "/opt/apps/superset/venv_py3_test/lib64/python3.4/site-packages/pandas/io/sql.py", line 975, in execute
    return self.connectable.execute(*args, **kwargs)
  File "/opt/apps/superset/venv_py3_test/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 2064, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/opt/apps/superset/venv_py3_test/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 939, in execute
    return self._execute_text(object, multiparams, params)
  File "/opt/apps/superset/venv_py3_test/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1097, in _execute_text
    statement, parameters
  File "/opt/apps/superset/venv_py3_test/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/opt/apps/superset/venv_py3_test/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/opt/apps/superset/venv_py3_test/lib64/python3.4/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/apps/superset/venv_py3_test/lib64/python3.4/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/opt/apps/superset/venv_py3_test/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/opt/apps/superset/venv_py3_test/lib64/python3.4/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: test_superset_view [SQL: 'SELECT DISTINCT id AS id \nFROM test_superset_view\n LIMIT 10000 OFFSET 0']
```

As stated before: as far as I understand, the query should be run against the subquery that is defined by the superset view, rather than just against its table name.

**Comment by mistercrunch** [comment]
Oh I understand now.

**Comment by mistercrunch** [comment]
Here's the fix https://github.com/airbnb/superset/pull/2816

**Comment by rumbin** [comment]
Thanks for the quick fix!
