### ISSUE TITLE
Console error when selecting dropdowns for slice configuration

### ISSUE THREAD

**Issue by kelchm** [airbnb/superset#2892]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.3

### Steps to reproduce
While editing a slice, select any of the dropdowns in sidebar.

### Expected results
I should receive a dropdown of relevant options (a list of tables, time-related options, etc...)

### Actual results
No dropdown appears and a js error is seen in the browsers console.

```
Uncaught ReferenceError: opt is not defined
    at e (http://10.1.1.246:8088/static/assets/dist/explore.0.18.3.entry.js:191:194649)
    at http://10.1.1.246:8088/static/assets/dist/explore.0.18.3.entry.js:103:72498
    at Array.map (native)
    at Object.i [as menuRenderer] (http://10.1.1.246:8088/static/assets/dist/explore.0.18.3.entry.js:103:72147)
    at Object.renderMenu (http://10.1.1.246:8088/static/assets/dist/explore.0.18.3.entry.js:34:17512)
    at Object.renderOuter (http://10.1.1.246:8088/static/assets/dist/explore.0.18.3.entry.js:34:18865)
    at Object.render (http://10.1.1.246:8088/static/assets/dist/explore.0.18.3.entry.js:34:20971)
    at d._renderValidatedComponentWithoutOwnerOrContext (http://10.1.1.246:8088/static/assets/dist/explore.0.18.3.entry.js:135:178254)
    at d._renderValidatedComponent (http://10.1.1.246:8088/static/assets/dist/explore.0.18.3.entry.js:135:178381)
    at d._updateRenderedComponent (http://10.1.1.246:8088/static/assets/dist/explore.0.18.3.entry.js:135:177685)
```

EDIT: This seems to be a new issue with 0.18.3.

**Comment by davidhassan** [comment]
Looks like the latest build has failed for javascript. ie Pull Request #2818 add validation rule for visualize

**Comment by ascott** [comment]
@davidhassan #2818 hasn't been merged yet. 

@kelchm the fix is in master now. https://github.com/airbnb/superset/commit/04fb0e2c2d2bc3747b67d083b3a6981a18d03b15

**Comment by mi-lee** [comment]
I'm also receiving this error as well, when I select the "Group By" metrics dropdown. This is using the sample data.

**Comment by mistercrunch** [comment]
Packaging `0.18.4`  as I write this, should be out in a few minutes
