### ISSUE TITLE
[Sources > Tables] Console errors when selecting Metrics dropdowns

### ISSUE THREAD

**Issue by mi-lee** [airbnb/superset#2905]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.18.3

### Expected results

In the `explore/table/:id` pages, a dropdown of relevant options should show. 

### Actual results

Console errors below show:

```
explore.0.18.3.entry.js:191 Uncaught ReferenceError: opt is not defined
    at e (http://localhost:8088/static/assets/dist/explore.0.18.3.entry.js:191:194656)
    at http://localhost:8088/static/assets/dist/explore.0.18.3.entry.js:103:72498
    at Array.map (native)
    at Object.i [as menuRenderer] (http://localhost:8088/static/assets/dist/explore.0.18.3.entry.js:103:72147)
    at Object.renderMenu (http://localhost:8088/static/assets/dist/explore.0.18.3.entry.js:34:17512)
    at Object.renderOuter (http://localhost:8088/static/assets/dist/explore.0.18.3.entry.js:34:18865)
    at Object.render (http://localhost:8088/static/assets/dist/explore.0.18.3.entry.js:34:20971)
    at d._renderValidatedComponentWithoutOwnerOrContext (http://localhost:8088/static/assets/dist/explore.0.18.3.entry.js:135:178254)
    at d._renderValidatedComponent (http://localhost:8088/static/assets/dist/explore.0.18.3.entry.js:135:178381)
    at d._updateRenderedComponent (http://localhost:8088/static/assets/dist/explore.0.18.3.entry.js:135:177685)
    at d._performComponentUpdate (http://localhost:8088/static/assets/dist/explore.0.18.3.entry.js:135:177486)
    at d.updateComponent (http://localhost:8088/static/assets/dist/explore.0.18.3.entry.js:135:176764)
    at d.performUpdateIfNecessary (http://localhost:8088/static/assets/dist/explore.0.18.3.entry.js:135:176097)
    at Object.performUpdateIfNecessary (http://localhost:8088/static/assets/dist/explore.0.18.3.entry.js:29:109283)
    at s (http://localhost:8088/static/assets/dist/explore.0.18.3.entry.js:29:85098)
    at r.perform (http://localhost:8088/static/assets/dist/explore.0.18.3.entry.js:34:51565)
    at i.perform (http://localhost:8088/static/assets/dist/explore.0.18.3.entry.js:34:51565)
    at i.perform (http://localhost:8088/static/assets/dist/explore.0.18.3.entry.js:29:86162)
    at Object.E [as flushBatchedUpdates] (http://localhost:8088/static/assets/dist/explore.0.18.3.entry.js:29:86331)
    at r.closeAll (http://localhost:8088/static/assets/dist/explore.0.18.3.entry.js:34:52153)
    at r.perform (http://localhost:8088/static/assets/dist/explore.0.18.3.entry.js:34:51648)
    at Object.batchedUpdates (http://localhost:8088/static/assets/dist/explore.0.18.3.entry.js:135:198831)
    at Object.o [as batchedUpdates] (http://localhost:8088/static/assets/dist/explore.0.18.3.entry.js:29:84685)
    at dispatchEvent (http://localhost:8088/static/assets/dist/explore.0.18.3.entry.js:135:201412)
```

### Steps to reproduce

1. Follow steps here http://airbnb.io/superset/installation.html#superset-installation-and-initialization
2. Navigate to `random_time_series` datasource from `load_examples`, i.e. http://localhost:8088/superset/explore/table/4/. 
3. Click on any dropdowns. 

This sounds like https://github.com/airbnb/superset/issues/2892 except it's for Sources/Tables, not Slice configuration.

**Comment by mistercrunch** [comment]
Releasing `0.18.4` with a fix for this
https://github.com/airbnb/superset/commit/04fb0e2c2d2bc3747b67d083b3a6981a18d03b15

**Comment by mi-lee** [comment]
Thanks for the quick response!
