### ISSUE TITLE
OSError: [Errno 92] Protocol not available

### ISSUE THREAD

**Issue by toncek87** [airbnb/superset#3002]
Maybe it is dummy question, but If i run: `superset runserver` without parameter -d there is error

`Starting server with command: gunicorn -w 2 --timeout 60 -b  0.0.0.0:8088 --limit-request-line 0 --limit-request-field_size 0 superset:app
[2017-06-20 15:00:03 +0200] [7258] [INFO] Starting gunicorn 19.7.1
Traceback (most recent call last):
  File "/virtual/superset-test/lib/python3.4/site-packages/gunicorn/sock.py", line 44, in set_options
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1)
OSError: [Errno 92] Protocol not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/virtual/superset-test/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/virtual/superset-test/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/virtual/superset-test/lib/python3.4/site-packages/gunicorn/app/base.py", line 203, in run
    super(Application, self).run()
  File "/virtual/superset-test/lib/python3.4/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/virtual/superset-test/lib/python3.4/site-packages/gunicorn/arbiter.py", line 198, in run
    self.start()
  File "/virtual/superset-test/lib/python3.4/site-packages/gunicorn/arbiter.py", line 157, in start
    self.LISTENERS = sock.create_sockets(self.cfg, self.log, fds)
  File "/virtual/superset-test/lib/python3.4/site-packages/gunicorn/sock.py", line 180, in create_sockets
    sock = sock_type(addr, conf, log)
  File "/virtual/superset-test/lib/python3.4/site-packages/gunicorn/sock.py", line 32, in __init__
    self.sock = self.set_options(sock, bound=bound)
  File "/virtual/superset-test/lib/python3.4/site-packages/gunicorn/sock.py", line 89, in set_options
    return super(TCPSocket, self).set_options(sock, bound=bound)
  File "/virtual/superset-test/lib/python3.4/site-packages/gunicorn/sock.py", line 46, in set_options
    if err[0] not in (errno.ENOPROTOOPT, errno.EINVAL):
TypeError: 'OSError' object is not subscriptable`

If i run: `superset runserver -d` superset works... what is wrong?

**Comment by xrmx** [comment]
What operating system / environment is this?

**Comment by xrmx** [comment]
Anyway this looks like https://github.com/benoitc/gunicorn/issues/1501

**Comment by toncek87** [comment]
[benoitc/gunicorn#1501](https://github.com/benoitc/gunicorn/issues/1501) - it works

**Comment by xrmx** [comment]
Closing then
