### ISSUE TITLE
Can't run query in SQL Lab

### ISSUE THREAD

**Issue by alexisrosuel** [airbnb/superset#3016]
Hello, 

My Superset version is 0.18.4

I connected some database (postgres) to Superset, and I assume they are working properly because I created some slices and dashboards from them (and it works). 

But when I want to use SQL Lab, I always got the following error : 
![capture d ecran 2017-06-21 a 13 39 27](https://user-images.githubusercontent.com/19517275/27382408-1e5360bc-5687-11e7-9339-46c882026085.png)

Do you also have this issue ?

Thank you,

Alexis

**Comment by xrmx** [comment]
Please post the full error in text, not as picture

**Comment by alexisrosuel** [comment]
Here it is : 

```
sqlalchemy.exc.ProgrammingError
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column query.end_result_backend_time does not exist
LINE 1: ...t_running_time, query.end_time AS query_end_time, query.end_...
                                                             ^
 [SQL: 'SELECT query.id AS query_id, query.client_id AS query_client_id, query.database_id AS query_database_id, query.tmp_table_name AS query_tmp_table_name, query.user_id AS query_user_id, query.status AS query_status, query.tab_name AS query_tab_name, query.sql_editor_id AS query_sql_editor_id, query.schema AS query_schema, query.sql AS query_sql, query.select_sql AS query_select_sql, query.executed_sql AS query_executed_sql, query."limit" AS query_limit, query.limit_used AS query_limit_used, query.select_as_cta AS query_select_as_cta, query.select_as_cta_used AS query_select_as_cta_used, query.progress AS query_progress, query.rows AS query_rows, query.error_message AS query_error_message, query.results_key AS query_results_key, query.start_time AS query_start_time, query.start_running_time AS query_start_running_time, query.end_time AS query_end_time, query.end_result_backend_time AS query_end_result_backend_time, query.changed_on AS query_changed_on \nFROM query \n LIMIT %(param_1)s'] [parameters: {'param_1': 100}]

Traceback (most recent call last)
File "/app/.heroku/python/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
return self.wsgi_app(environ, start_response)
File "/app/.heroku/python/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
response = self.handle_exception(e)
File "/app/.heroku/python/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
reraise(exc_type, exc_value, tb)
File "/app/.heroku/python/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
raise value
File "/app/.heroku/python/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/app/.heroku/python/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/app/.heroku/python/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/app/.heroku/python/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
raise value
File "/app/.heroku/python/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "/app/.heroku/python/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/app/.heroku/python/lib/python3.5/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
return f(self, *args, **kwargs)
File "/app/.heroku/python/lib/python3.5/site-packages/flask_appbuilder/views.py", line 450, in list
widgets = self._list()
File "/app/.heroku/python/lib/python3.5/site-packages/flask_appbuilder/baseviews.py", line 870, in _list
page_size=page_size)
File "/app/.heroku/python/lib/python3.5/site-packages/flask_appbuilder/baseviews.py", line 786, in _get_list_widget
count, lst = self.datamodel.query(joined_filters, order_column, order_direction, page=page, page_size=page_size)
File "/app/.heroku/python/lib/python3.5/site-packages/flask_appbuilder/models/sqla/interface.py", line 112, in query
return count, query.all()
File "/app/.heroku/python/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2703, in all
return list(self)
File "/app/.heroku/python/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
return self._execute_and_instances(context)
File "/app/.heroku/python/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
result = conn.execute(querycontext.statement, self._params)
File "/app/.heroku/python/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 945, in execute
return meth(self, multiparams, params)
File "/app/.heroku/python/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
return connection._execute_clauseelement(self, multiparams, params)
File "/app/.heroku/python/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
compiled_sql, distilled_params
File "/app/.heroku/python/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
context)
File "/app/.heroku/python/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
exc_info
File "/app/.heroku/python/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb, cause=cause)
File "/app/.heroku/python/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
raise value.with_traceback(tb)
File "/app/.heroku/python/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
context)
File "/app/.heroku/python/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column query.end_result_backend_time does not exist LINE 1: ...t_running_time, query.end_time AS query_end_time, query.end_... ^ [SQL: 'SELECT query.id AS query_id, query.client_id AS query_client_id, query.database_id AS query_database_id, query.tmp_table_name AS query_tmp_table_name, query.user_id AS query_user_id, query.status AS query_status, query.tab_name AS query_tab_name, query.sql_editor_id AS query_sql_editor_id, query.schema AS query_schema, query.sql AS query_sql, query.select_sql AS query_select_sql, query.executed_sql AS query_executed_sql, query."limit" AS query_limit, query.limit_used AS query_limit_used, query.select_as_cta AS query_select_as_cta, query.select_as_cta_used AS query_select_as_cta_used, query.progress AS query_progress, query.rows AS query_rows, query.error_message AS query_error_message, query.results_key AS query_results_key, query.start_time AS query_start_time, query.start_running_time AS query_start_running_time, query.end_time AS query_end_time, query.end_result_backend_time AS query_end_result_backend_time, query.changed_on AS query_changed_on \nFROM query \n LIMIT %(param_1)s'] [parameters: {'param_1': 100}]
```

**Comment by xrmx** [comment]
Looks like a dup of #2770
